### ISSUE TITLE
Link to channels on mobile takes you to channel info instead of opening the actual channel

### ISSUE THREAD

**Issue by b4ps** [Mobility4PS/Rocket.Chat.ReactNative#13]
- Your Rocket.Chat Experimental app version: 4.8.1
- Your Rocket.Chat server version: ####
- Device (or Simulator) you're running with: ####

**The app isn't connecting to your server?**
Make sure your server supports WebSocket. These are the minimum requirements for Apache 2.4 and Nginx 1.3 or greater.

**Comment by cprice-kgi** [comment]
a link to a channel embedded in a chat message goes to the channel info page rather than to the actual channel like it does on the web/server version.

**Comment by cprice-kgi** [comment]
![Screen Shot 2020-08-05 at 10 49 53 AM](https://user-images.githubusercontent.com/56982873/89427795-a324d900-d709-11ea-9296-2972d02e060e.png)

**Comment by cprice-kgi** [comment]
updated to take user to channel instead of channel info. a few instances on ipad-style layout will still go to channel info due to modal window navigation. the "main" way (directly from room messages) will go to channels across both tablet/phone devices.
