### ISSUE TITLE
Admin panel now link in browser instead of embedded in app

### ISSUE THREAD

**Issue by b4ps** [Mobility4PS/Rocket.Chat.ReactNative#14]

**Comment by cprice-kgi** [comment]
a link to a channel embedded in a chat message goes to the channel info page rather than to the actual channel like it does on the web/server version.

**Comment by cprice-kgi** [comment]
![Screen Shot 2020-08-05 at 10 49 53 AM](https://user-images.githubusercontent.com/56982873/89427683-89839180-d709-11ea-97d5-d5250867a4ff.png)

**Comment by b4ps** [comment]
Admin panel works correctly in the Android app but iOS directs me to login via browser.
